class StatsCols:
    """
    Class holding players game stats column names.
    """
    GAME_ID = 'game_id'
    PLAYER_ID = 'player_id'
    PLAYER_NAME = 'player_name'
    TEAM_ID = 'team_id'
    TEAM_NAME = 'team_name'
    TEAM_ACRONYM = 'team_acronym'
    ROLE = 'role'
    WIN = 'win'
    GAME_LENGTH = 'game_length'
    CHAMPION_NAME = 'champion_name'
    TEAM_KILLS = 'team_kills'
    TOWER_KILLS = 'tower_kills'
    INHIBITOR_KILLS = 'inhibitor_kills'
    DRAGON_KILLS = 'dragon_kills'
    HERALD_KILLS = 'herald_kills'
    BARON_KILLS = 'baron_kills'
    PLAYER_KILLS = 'player_kills'
    PLAYER_DEATHS = 'player_deaths'
    PLAYER_ASSISTS = 'player_assists'
    TOTAL_MINIONS_KILLED = 'total_minions_killed'
    GOLD_EARNED = 'gold_earned'
    LEVEL = 'level'
    TOTAL_DAMAGE_DEALT = 'total_damage_dealt'
    TOTAL_DAMAGE_DEALT_TO_CHAMPIONS = 'total_damage_dealt_to_champions'
    TOTAL_DAMAGE_TAKEN = 'total_damage_taken'
    WARDS_PLACED = 'wards_placed'
    LARGEST_KILLING_SPREE = 'largest_killing_spree'
    LARGEST_MULTI_KILL = 'largest_multi_kill'
